sudo: required
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install unzip build-essential libtool git subversion cmake libfreeimage-dev libatlas3gf-base libatlas-dev libfftw3-dev liblapacke-dev libboost1.55-all-dev libglew-dev libglewmx-dev xorg-dev libglu1-mesa-dev
    - wget https://github.com/glfw/glfw/releases/download/3.1.2/glfw-3.1.2.zip
    - unzip glfw-3.1.2.zip -d . && cd glfw-3.1.2 && cmake . && sudo make install
    - cd .. && git submodule update --init --recursive

language: rust
script:
    - sed -i -- 's/true/false/g' /home/travis/build/jramapuram/hal/arrayfire-rust/build.conf
    - cargo build --verbose
    - cargo test
    - cargo run --example autoencoder
rust:
    - 1.7.0
env:
  global:
    - AF_PATH=/home/travis/build/jramapuram/hal/arrayfire-rust/arrayfire/build/package/lib
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$AF_PATH
    - RUST_TEST_THREADS=1
